# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.daemon.idletimeout=60000

android.useAndroidX=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false
kotlin.code.style=official
ksp.useKSP2=true
kotlin.daemon.jvm.options=-Xmx1024m -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40
