# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3078m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false
kotlin.code.style=official
ksp.useKSP2=true
